export const ADD_PRODUCT = 'ADD_PRODUCT'

export const ADD_CARTLIST = 'ADD_CARTLIST'

export const GET_CARTLIST = 'GET_CARTLIST'

export const GET_PRODUCT = 'GET_PRODUCT'

export const UPDATE_CONTENT = 'UPDATE_CONTENT'

export const DELETE_CONTENT = 'DELETE_CONTENT'